# Generated by Django 5.0.7 on 2024-08-30 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_carinventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carinventory',
            old_name='cars_value',
            new_name='cars_value',
        ),
    ]
